AuctionTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: AuctionsTable-${self:provider.stage}
    BillingMode: PROVISIONED
    ProvisionedThroughput:
     ReadCapacityUnits: 1 ###free tier eligible up to 10
     WriteCapacityUnits: 1
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: endingDate
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: statusAndEndDateGSI
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: endingDate
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
         ReadCapacityUnits: 1 ###free tier eligible up to 10
         WriteCapacityUnits: 1

AuctionsS3ImagesBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.AuctionsS3ImagesBucket.name}
    LifecycleConfiguration:
      Rules:
        - Id: AuctionPicturesExpiration
          Status: Enabled
          ExpirationInDays: 1 ##uploaded images will be deleted after 1 day
AuctionsS3ImagesBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref AuctionsS3ImagesBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.AuctionsS3ImagesBucket.name}/*